export interface LabModel {
  name: string;
  type: "text" | "multimodal" | "image" | "code" | "embedding" | "reasoning";
  contextWindow?: string;
  inputPrice?: string;
  outputPrice?: string;
  freeAccess?: boolean;
  highlight?: string;
  speed?: "fast" | "medium" | "slow";
}

export interface AILab {
  id: string;
  name: string;
  tagline: string;
  emoji: string;
  color: string;
  type: "frontier" | "open-source" | "enterprise" | "specialized";
  founded: string;
  hq: string;
  website: string;
  focus: string[];
  description: string;
  models: LabModel[];
  products: string[];
  api: {
    available: boolean;
    endpoint?: string;
    sdks?: string[];
  };
  strengths: string[];
  useCases: string[];
}

export const AI_LABS: AILab[] = [
  {
    id: "anthropic",
    name: "Anthropic",
    tagline: "AI safety company building reliable, interpretable, and steerable AI systems",
    emoji: "🔬",
    color: "#9F8CFF",
    type: "frontier",
    founded: "2021",
    hq: "San Francisco, CA",
    website: "https://anthropic.com",
    focus: ["Safety", "Long context", "Agentic AI", "Code"],
    description:
      "Anthropic is an AI safety company founded by former OpenAI researchers, focused on building AI systems that are safe, beneficial, and understandable. Their Constitutional AI approach and RLHF techniques underpin the Claude model family. Claude models excel at long-context reasoning, nuanced writing, and complex agentic tasks.",
    models: [
      {
        name: "Claude Haiku 4.5",
        type: "text",
        contextWindow: "200K tokens",
        inputPrice: "$0.80 / M tokens",
        outputPrice: "$4 / M tokens",
        freeAccess: false,
        highlight: "Best for high-volume, latency-sensitive tasks",
        speed: "fast",
      },
      {
        name: "Claude Sonnet 4.6",
        type: "text",
        contextWindow: "200K tokens",
        inputPrice: "$3 / M tokens",
        outputPrice: "$15 / M tokens",
        freeAccess: false,
        highlight: "Optimal balance of intelligence and speed",
        speed: "medium",
      },
      {
        name: "Claude Opus 4.7",
        type: "text",
        contextWindow: "200K tokens",
        inputPrice: "$15 / M tokens",
        outputPrice: "$75 / M tokens",
        freeAccess: false,
        highlight: "Deepest reasoning, long-horizon tasks",
        speed: "slow",
      },
    ],
    products: [
      "Claude.ai",
      "Claude API",
      "Claude Code",
      "Claude for Work",
      "Amazon Bedrock integration",
    ],
    api: {
      available: true,
      endpoint: "api.anthropic.com",
      sdks: ["Python", "TypeScript"],
    },
    strengths: [
      "Constitutional AI safety and alignment",
      "Best-in-class long-context reasoning",
      "Coding excellence across all major languages",
      "Nuanced, high-quality writing and analysis",
      "Reliable multi-step agentic task execution",
    ],
    useCases: [
      "Complex document analysis and summarization",
      "Software engineering and code review",
      "Long-form content creation and editing",
      "Multi-step research and reasoning tasks",
      "Enterprise AI assistants requiring safety guardrails",
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    tagline: "Building safe AGI that benefits all of humanity",
    emoji: "🤖",
    color: "#10a37f",
    type: "frontier",
    founded: "2015",
    hq: "San Francisco, CA",
    website: "https://openai.com",
    focus: ["AGI", "Multimodal", "Reasoning", "Agents"],
    description:
      "OpenAI pioneered large-scale language model research and brought AI to mass adoption with ChatGPT. The company pursues artificial general intelligence through a capped-profit structure, with major investments from Microsoft. Their model portfolio spans text, image, audio, and video, and their reasoning models (o-series) set benchmarks in math and science.",
    models: [
      {
        name: "GPT-4o",
        type: "multimodal",
        contextWindow: "128K tokens",
        inputPrice: "$2.50 / M tokens",
        outputPrice: "$10 / M tokens",
        freeAccess: false,
        highlight: "Vision, audio, and text in one model",
        speed: "medium",
      },
      {
        name: "GPT-4o mini",
        type: "multimodal",
        contextWindow: "128K tokens",
        inputPrice: "$0.15 / M tokens",
        outputPrice: "$0.60 / M tokens",
        freeAccess: false,
        highlight: "Cost-efficient for simple tasks",
        speed: "fast",
      },
      {
        name: "o3",
        type: "reasoning",
        contextWindow: "200K tokens",
        inputPrice: "$10 / M tokens",
        outputPrice: "$40 / M tokens",
        freeAccess: false,
        highlight: "State-of-the-art math, science, code reasoning",
        speed: "slow",
      },
      {
        name: "o4-mini",
        type: "reasoning",
        contextWindow: "200K tokens",
        inputPrice: "$1.10 / M tokens",
        outputPrice: "$4.40 / M tokens",
        freeAccess: false,
        highlight: "Fast reasoning for complex problems",
        speed: "medium",
      },
      {
        name: "GPT-image-1",
        type: "image",
        freeAccess: false,
        highlight: "Flagship image generation model",
      },
    ],
    products: [
      "ChatGPT",
      "DALL-E 3",
      "Whisper",
      "Sora",
      "Operator",
      "GPT Store",
      "Azure OpenAI",
    ],
    api: {
      available: true,
      endpoint: "api.openai.com",
      sdks: ["Python", "TypeScript", "Java", ".NET", "Go"],
    },
    strengths: [
      "Largest AI ecosystem and developer community",
      "Best-in-class multimodal understanding (vision, audio)",
      "Frontier reasoning via o-series models",
      "Seamless Azure cloud enterprise integration",
      "Widest range of modalities and specialized models",
    ],
    useCases: [
      "Multimodal applications with vision and audio",
      "Advanced reasoning for STEM problems",
      "Consumer AI products with broad capability needs",
      "Enterprise deployments via Azure OpenAI",
      "Image and video generation workflows",
    ],
  },
  {
    id: "google-deepmind",
    name: "Google DeepMind",
    tagline: "Advancing science and benefiting humanity through AI research",
    emoji: "🧠",
    color: "#4285F4",
    type: "frontier",
    founded: "2010",
    hq: "London, UK / Mountain View, CA",
    website: "https://deepmind.google",
    focus: ["Multimodal", "Long context", "Scientific AI", "Search"],
    description:
      "Google DeepMind combines the research firepower of DeepMind with Google Brain, backed by Google's unmatched infrastructure and data advantages. The Gemini model family leads on ultra-long context windows (up to 1M tokens) and multimodal understanding. DeepMind's research spans protein folding, game-playing AI, and large-scale scientific discovery.",
    models: [
      {
        name: "Gemini 2.5 Flash",
        type: "multimodal",
        contextWindow: "1M tokens",
        inputPrice: "$0.15 / M tokens",
        outputPrice: "$0.60 / M tokens",
        freeAccess: false,
        highlight: "Ultra-long context at low cost",
        speed: "fast",
      },
      {
        name: "Gemini 2.5 Pro",
        type: "multimodal",
        contextWindow: "1M tokens",
        inputPrice: "$1.25 / M tokens",
        outputPrice: "$10 / M tokens",
        freeAccess: false,
        highlight: "1M token context, best multimodal performance",
        speed: "medium",
      },
      {
        name: "Gemini 2.5 Ultra",
        type: "multimodal",
        contextWindow: "1M tokens",
        inputPrice: "Enterprise pricing",
        outputPrice: "Enterprise pricing",
        freeAccess: false,
        highlight: "Frontier research and complex reasoning",
        speed: "slow",
      },
      {
        name: "Imagen 3",
        type: "image",
        freeAccess: false,
        highlight: "Google's highest-quality text-to-image model",
      },
    ],
    products: [
      "Gemini (app)",
      "Google AI Studio",
      "Vertex AI",
      "NotebookLM",
      "Google Search AI",
    ],
    api: {
      available: true,
      endpoint: "generativelanguage.googleapis.com",
      sdks: ["Python", "JavaScript", "Go", "Swift", "Android"],
    },
    strengths: [
      "Industry-leading 1M token context window",
      "Native multimodal from the ground up",
      "Deep Google Search and Knowledge Graph integration",
      "Massive compute via Google TPU infrastructure",
      "Strong scientific and mathematical reasoning",
    ],
    useCases: [
      "Whole-document or codebase analysis in a single prompt",
      "Multimodal tasks combining text, image, and video",
      "Search-grounded question answering",
      "Scientific research and data analysis",
      "Enterprise AI on Google Cloud (Vertex AI)",
    ],
  },
  {
    id: "meta-ai",
    name: "Meta AI",
    tagline: "Open and efficient AI models for everyone",
    emoji: "🦙",
    color: "#0082fb",
    type: "open-source",
    founded: "2013",
    hq: "Menlo Park, CA",
    website: "https://ai.meta.com",
    focus: ["Open Source", "Social AI", "Multimodal", "Efficiency"],
    description:
      "Meta AI releases its Llama model family as open-weight models under permissive licenses, enabling the broadest self-hosted AI ecosystem in the industry. The Llama 3 series matches or exceeds many closed frontier models at a fraction of the cost. Meta integrates AI across its 3B+ user platforms—Facebook, Instagram, and WhatsApp.",
    models: [
      {
        name: "Llama 3.3 70B",
        type: "text",
        contextWindow: "128K tokens",
        freeAccess: true,
        highlight: "Top open-source model, Apache 2.0 license",
        speed: "medium",
      },
      {
        name: "Llama 3.1 405B",
        type: "text",
        contextWindow: "128K tokens",
        freeAccess: true,
        highlight: "Largest open model, matches frontier performance",
        speed: "slow",
      },
      {
        name: "Llama 4 Scout",
        type: "multimodal",
        contextWindow: "128K tokens",
        freeAccess: true,
        highlight: "Efficient multimodal open model",
        speed: "fast",
      },
      {
        name: "Llama 4 Maverick",
        type: "multimodal",
        contextWindow: "128K tokens",
        freeAccess: true,
        highlight: "Meta's most capable open model",
        speed: "medium",
      },
    ],
    products: [
      "Meta AI assistant",
      "Llama model zoo",
      "CodeLlama",
      "WhatsApp AI",
      "Ray-Ban Meta (wearables)",
    ],
    api: {
      available: true,
      endpoint: "api.meta.ai",
      sdks: ["Python"],
    },
    strengths: [
      "Fully open weights—self-host, fine-tune, deploy anywhere",
      "Apache 2.0 license enables commercial use at zero licensing cost",
      "Massive fine-tuning community and model hub",
      "Competitive performance with closed frontier models",
      "Native integration across Meta's social platforms",
    ],
    useCases: [
      "Self-hosted inference with full data privacy",
      "Fine-tuning on proprietary datasets without data sharing",
      "High-volume inference where API costs are prohibitive",
      "Research and academic projects needing model access",
      "On-device and edge deployment",
    ],
  },
  {
    id: "mistral-ai",
    name: "Mistral AI",
    tagline: "Frontier AI built in Europe, efficient and open by design",
    emoji: "💨",
    color: "#FF7000",
    type: "frontier",
    founded: "2023",
    hq: "Paris, France",
    website: "https://mistral.ai",
    focus: ["European AI", "Efficiency", "Open weights", "Code"],
    description:
      "Mistral AI is Europe's leading frontier AI lab, known for releasing highly efficient models that punch well above their weight class. The company balances open-weight releases (Mistral 7B, Mixtral 8x7B) with proprietary frontier models on la Plateforme. Codestral is a purpose-built coding model supporting over 80 programming languages.",
    models: [
      {
        name: "Mistral Small 3.1",
        type: "text",
        contextWindow: "128K tokens",
        inputPrice: "$0.10 / M tokens",
        outputPrice: "$0.30 / M tokens",
        freeAccess: false,
        highlight: "Best price-performance for straightforward tasks",
        speed: "fast",
      },
      {
        name: "Mistral Large 2",
        type: "text",
        contextWindow: "128K tokens",
        inputPrice: "$2 / M tokens",
        outputPrice: "$6 / M tokens",
        freeAccess: false,
        highlight: "Top European frontier model",
        speed: "medium",
      },
      {
        name: "Codestral",
        type: "code",
        contextWindow: "256K tokens",
        inputPrice: "$0.20 / M tokens",
        outputPrice: "$0.60 / M tokens",
        freeAccess: false,
        highlight: "Purpose-built for code, 80+ languages",
        speed: "fast",
      },
      {
        name: "Pixtral Large",
        type: "multimodal",
        contextWindow: "128K tokens",
        inputPrice: "$2 / M tokens",
        outputPrice: "$6 / M tokens",
        freeAccess: false,
        highlight: "Frontier multimodal with document understanding",
        speed: "medium",
      },
    ],
    products: [
      "Le Chat",
      "la Plateforme (API)",
      "Mistral Agents",
      "Mistral 7B (open-weight)",
      "Mixtral 8x7B (open-weight)",
    ],
    api: {
      available: true,
      endpoint: "api.mistral.ai",
      sdks: ["Python", "TypeScript"],
    },
    strengths: [
      "Exceptional efficiency—strong results at small model sizes",
      "Open-weight releases for community and research use",
      "GDPR-compliant European data residency options",
      "Codestral sets the bar for specialized code models",
      "Competitive frontier performance at lower cost than US labs",
    ],
    useCases: [
      "Cost-sensitive production APIs needing frontier quality",
      "European enterprises requiring data sovereignty",
      "Code completion and developer tooling",
      "Fine-tuning on open-weight base models",
      "Multilingual European-language tasks",
    ],
  },
  {
    id: "xai",
    name: "xAI",
    tagline: "Understanding the universe through real-time, unfiltered AI",
    emoji: "⚡",
    color: "#1DA1F2",
    type: "frontier",
    founded: "2023",
    hq: "Palo Alto, CA",
    website: "https://x.ai",
    focus: ["Real-time info", "Unfiltered AI", "X/Twitter integration", "Research"],
    description:
      "xAI was founded by Elon Musk with a mission to build AI that genuinely understands the physical universe. Grok models have a unique advantage: real-time access to X (Twitter) data, giving them up-to-the-minute awareness of world events. The lab emphasizes fewer content restrictions compared to other frontier providers.",
    models: [
      {
        name: "Grok 3",
        type: "text",
        contextWindow: "131K tokens",
        inputPrice: "$5 / M tokens",
        outputPrice: "$15 / M tokens",
        freeAccess: false,
        highlight: "Real-time X/Twitter data access",
        speed: "medium",
      },
      {
        name: "Grok 3 Mini",
        type: "reasoning",
        contextWindow: "131K tokens",
        inputPrice: "$0.30 / M tokens",
        outputPrice: "$0.50 / M tokens",
        freeAccess: false,
        highlight: "Fast reasoning for complex problems at low cost",
        speed: "fast",
      },
      {
        name: "Aurora",
        type: "image",
        freeAccess: false,
        highlight: "xAI's photorealistic image generation model",
      },
    ],
    products: [
      "Grok (X integration)",
      "xAI API",
      "Aurora image generation",
    ],
    api: {
      available: true,
      endpoint: "api.x.ai",
      sdks: ["Python", "TypeScript"],
    },
    strengths: [
      "Unique real-time access to X/Twitter firehose data",
      "Up-to-the-minute awareness of current events",
      "Less restrictive content policies than competitor labs",
      "Competitive frontier reasoning performance",
      "Tight integration with the X social platform ecosystem",
    ],
    useCases: [
      "Real-time news analysis and social media monitoring",
      "Current events Q&A requiring up-to-date information",
      "Applications embedded within the X platform",
      "Research requiring less filtered model outputs",
      "Trend detection and social intelligence workflows",
    ],
  },
  {
    id: "cohere",
    name: "Cohere",
    tagline: "Enterprise AI that understands your business data",
    emoji: "🏢",
    color: "#39594D",
    type: "enterprise",
    founded: "2019",
    hq: "Toronto, Canada",
    website: "https://cohere.com",
    focus: ["Enterprise RAG", "Embeddings", "Grounded generation", "Private deployment"],
    description:
      "Cohere focuses exclusively on enterprise AI, with best-in-class retrieval-augmented generation (RAG) and embedding models. Their Command series is optimized for business workflows requiring grounded, accurate responses from company knowledge bases. Cohere offers flexible deployment options including private cloud and on-premises installs for regulated industries.",
    models: [
      {
        name: "Command R+",
        type: "text",
        contextWindow: "128K tokens",
        inputPrice: "$2.50 / M tokens",
        outputPrice: "$10 / M tokens",
        freeAccess: false,
        highlight: "Optimized for enterprise RAG workflows",
        speed: "medium",
      },
      {
        name: "Command A",
        type: "text",
        contextWindow: "256K tokens",
        inputPrice: "$2.50 / M tokens",
        outputPrice: "$10 / M tokens",
        freeAccess: false,
        highlight: "Latest enterprise command model with extended context",
        speed: "medium",
      },
      {
        name: "Embed 3",
        type: "embedding",
        inputPrice: "$0.10 / M tokens",
        freeAccess: false,
        highlight: "Best-in-class enterprise search embeddings",
      },
    ],
    products: [
      "Coral (enterprise chat)",
      "Cohere API",
      "NightSea",
      "Toolkit for RAG",
    ],
    api: {
      available: true,
      endpoint: "api.cohere.com",
      sdks: ["Python", "TypeScript", "Java", "Go"],
    },
    strengths: [
      "Best-in-class retrieval-augmented generation out of the box",
      "Industry-leading embedding models for semantic search",
      "Private cloud and on-premises deployment for compliance",
      "Native grounding to reduce hallucinations in enterprise contexts",
      "Purpose-built for enterprise knowledge management",
    ],
    useCases: [
      "Enterprise search over internal knowledge bases",
      "RAG pipelines for customer support and documentation",
      "Regulated industries needing private model deployment",
      "Semantic search and recommendation systems",
      "Multi-document synthesis for research and legal workflows",
    ],
  },
  {
    id: "amazon-aws",
    name: "Amazon AWS",
    tagline: "AI built for the cloud, integrated across the AWS ecosystem",
    emoji: "☁️",
    color: "#FF9900",
    type: "enterprise",
    founded: "2006",
    hq: "Seattle, WA",
    website: "https://aws.amazon.com/ai",
    focus: ["Cloud infrastructure", "Enterprise", "Model marketplace", "AWS integration"],
    description:
      "Amazon's AI efforts span both proprietary Nova models and the Bedrock model marketplace, which gives customers access to models from Anthropic, Meta, Mistral, and others through a unified AWS API. Nova models are optimized for price-performance on AWS workloads. Amazon Q brings generative AI into the core AWS developer and business tooling stack.",
    models: [
      {
        name: "Amazon Nova Micro",
        type: "text",
        contextWindow: "128K tokens",
        inputPrice: "$0.035 / M tokens",
        outputPrice: "$0.14 / M tokens",
        freeAccess: false,
        highlight: "Fastest and cheapest Nova model for simple tasks",
        speed: "fast",
      },
      {
        name: "Amazon Nova Lite",
        type: "multimodal",
        contextWindow: "300K tokens",
        inputPrice: "$0.06 / M tokens",
        outputPrice: "$0.24 / M tokens",
        freeAccess: false,
        highlight: "Low-cost multimodal with extended context",
        speed: "fast",
      },
      {
        name: "Amazon Nova Pro",
        type: "multimodal",
        contextWindow: "300K tokens",
        inputPrice: "$0.80 / M tokens",
        outputPrice: "$3.20 / M tokens",
        freeAccess: false,
        highlight: "Best price-performance for complex multimodal tasks",
        speed: "medium",
      },
      {
        name: "Amazon Titan Embed",
        type: "embedding",
        freeAccess: false,
        highlight: "Optimized embeddings for AWS search and RAG pipelines",
      },
    ],
    products: [
      "Amazon Bedrock",
      "Amazon SageMaker",
      "Amazon Q",
      "Amazon Rekognition",
      "Amazon Textract",
    ],
    api: {
      available: true,
      endpoint: "bedrock.amazonaws.com",
      sdks: ["Python (boto3)", "TypeScript", "Java", ".NET", "Go", "Rust"],
    },
    strengths: [
      "Amazon Bedrock offers a single API to 30+ models from multiple labs",
      "Deepest integration with AWS services (S3, Lambda, Glue, etc.)",
      "Highly competitive Nova pricing for high-throughput workloads",
      "Enterprise compliance—SOC2, HIPAA, FedRAMP, GDPR",
      "Strong managed fine-tuning and model customization via SageMaker",
    ],
    useCases: [
      "Enterprises already invested in the AWS ecosystem",
      "High-volume inference requiring predictable cloud pricing",
      "Multi-model applications via Bedrock's unified API",
      "Regulated industries needing AWS compliance certifications",
      "Document processing pipelines with Textract and Bedrock",
    ],
  },
];

export const LAB_TYPES = [
  { id: "all", label: "All Labs" },
  { id: "frontier", label: "Frontier AI" },
  { id: "open-source", label: "Open Source" },
  { id: "enterprise", label: "Enterprise" },
] as const;
