export type ModelTier = "flagship" | "balanced" | "efficient" | "reasoning" | "open";
export type ModelSpeed = "fast" | "medium" | "slow";

export interface ModelEntry {
  id: string;
  name: string;
  apiId?: string;
  provider: string;
  providerColor: string;
  releaseDate: string;
  releaseDateNum: number;

  tier: ModelTier;
  contextWindow: number;   // thousands of tokens (128 = 128k)
  outputLimit: number | null;    // thousands of tokens

  // USD per 1M tokens — null = no public API / unknown
  inputPrice: number | null;
  outputPrice: number | null;
  priceNote?: string;

  // Benchmarks 0-100, null = not reported
  mmlu: number | null;       // general knowledge
  gpqa: number | null;       // graduate science
  sweBench: number | null;   // software engineering (% resolved)
  mathAime: number | null;   // AIME 2024 accuracy %

  multimodal: boolean;
  extendedThinking: boolean;
  webSearch: boolean;
  codeExecution: boolean;
  openSource: boolean;

  speed: ModelSpeed;
  bestFor: string[];
  highlight: string;

  docsUrl: string;
  status: "available" | "preview" | "deprecated";
  lastVerified: string;
}

export const TIER_META: Record<ModelTier, { label: string; color: string; desc: string }> = {
  flagship:  { label: "Flagship",   color: "#d97706", desc: "Best quality, highest cost" },
  balanced:  { label: "Balanced",   color: "#9F8CFF", desc: "Quality + cost sweet spot" },
  efficient: { label: "Efficient",  color: "#10b981", desc: "Fast & cheap, surprisingly capable" },
  reasoning: { label: "Reasoning",  color: "#ec4899", desc: "Extended thinking, math & logic" },
  open:      { label: "Open",       color: "#06b6d4", desc: "Open weights, self-hostable" },
};

export const SPEED_META: Record<ModelSpeed, { label: string; color: string }> = {
  fast:   { label: "Fast",   color: "#10b981" },
  medium: { label: "Medium", color: "#f59e0b" },
  slow:   { label: "Slow",   color: "#ef4444" },
};

// Pricing is approximate and changes frequently — always verify at provider docs
export const AI_MODELS: ModelEntry[] = [
  // ── Anthropic ─────────────────────────────────────────────────────────────
  {
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    apiId: "claude-opus-4-8",
    provider: "Anthropic",
    providerColor: "#d97706",
    releaseDate: "May 2026",
    releaseDateNum: 202605,
    tier: "flagship",
    contextWindow: 200,
    outputLimit: 32,
    inputPrice: 15,
    outputPrice: 75,
    priceNote: "50% off with prompt caching",
    mmlu: 90,
    gpqa: 86,
    sweBench: 72,
    mathAime: 74,
    multimodal: true,
    extendedThinking: true,
    webSearch: false,
    codeExecution: false,
    openSource: false,
    speed: "slow",
    bestFor: ["Complex reasoning", "Long documents", "Research synthesis", "Advanced coding"],
    highlight: "Best-in-class on most reasoning benchmarks as of May 2026",
    docsUrl: "https://docs.anthropic.com/en/docs/about-claude/models",
    status: "available",
    lastVerified: "2026-05-28",
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    apiId: "claude-sonnet-4-6",
    provider: "Anthropic",
    providerColor: "#d97706",
    releaseDate: "Mar 2026",
    releaseDateNum: 202603,
    tier: "balanced",
    contextWindow: 200,
    outputLimit: 16,
    inputPrice: 3,
    outputPrice: 15,
    priceNote: "50% off with prompt caching",
    mmlu: 88,
    gpqa: 78,
    sweBench: 57,
    mathAime: 62,
    multimodal: true,
    extendedThinking: true,
    webSearch: false,
    codeExecution: false,
    openSource: false,
    speed: "medium",
    bestFor: ["Production apps", "Writing", "Data analysis", "Coding assistance"],
    highlight: "Best balance of quality and cost for API workloads",
    docsUrl: "https://docs.anthropic.com/en/docs/about-claude/models",
    status: "available",
    lastVerified: "2026-05-28",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    apiId: "claude-haiku-4-5-20251001",
    provider: "Anthropic",
    providerColor: "#d97706",
    releaseDate: "Oct 2025",
    releaseDateNum: 202510,
    tier: "efficient",
    contextWindow: 200,
    outputLimit: 8,
    inputPrice: 0.25,
    outputPrice: 1.25,
    priceNote: "50% off with prompt caching",
    mmlu: 81,
    gpqa: 58,
    sweBench: 40,
    mathAime: 31,
    multimodal: true,
    extendedThinking: false,
    webSearch: false,
    codeExecution: false,
    openSource: false,
    speed: "fast",
    bestFor: ["High-volume classification", "Quick summaries", "Chatbots", "Form extraction"],
    highlight: "Cheapest Claude with vision — ideal for scale",
    docsUrl: "https://docs.anthropic.com/en/docs/about-claude/models",
    status: "available",
    lastVerified: "2026-05-28",
  },

  // ── OpenAI ────────────────────────────────────────────────────────────────
  {
    id: "gpt-5",
    name: "GPT-5",
    apiId: "gpt-5",
    provider: "OpenAI",
    providerColor: "#10a37f",
    releaseDate: "May 2026",
    releaseDateNum: 202605,
    tier: "flagship",
    contextWindow: 256,
    outputLimit: 32,
    inputPrice: 10,
    outputPrice: 30,
    mmlu: 92,
    gpqa: 88,
    sweBench: 68,
    mathAime: 80,
    multimodal: true,
    extendedThinking: false,
    webSearch: true,
    codeExecution: true,
    openSource: false,
    speed: "medium",
    bestFor: ["Multimodal tasks", "Agentic workflows", "Complex instruction following"],
    highlight: "85% on ARC-AGI-2 — strongest OpenAI model at launch",
    docsUrl: "https://platform.openai.com/docs/models",
    status: "available",
    lastVerified: "2026-05-25",
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    apiId: "gpt-4o",
    provider: "OpenAI",
    providerColor: "#10a37f",
    releaseDate: "May 2024",
    releaseDateNum: 202405,
    tier: "balanced",
    contextWindow: 128,
    outputLimit: 16,
    inputPrice: 2.5,
    outputPrice: 10,
    priceNote: "Cached input: $1.25/1M",
    mmlu: 88.7,
    gpqa: 53.6,
    sweBench: 33,
    mathAime: 13,
    multimodal: true,
    extendedThinking: false,
    webSearch: true,
    codeExecution: true,
    openSource: false,
    speed: "fast",
    bestFor: ["Vision tasks", "Structured output", "Function calling", "Real-time voice"],
    highlight: "Fast multimodal with native audio — still widely deployed",
    docsUrl: "https://platform.openai.com/docs/models",
    status: "available",
    lastVerified: "2026-05-01",
  },
  {
    id: "o3",
    name: "o3",
    apiId: "o3",
    provider: "OpenAI",
    providerColor: "#10a37f",
    releaseDate: "Apr 2025",
    releaseDateNum: 202504,
    tier: "reasoning",
    contextWindow: 200,
    outputLimit: 100,
    inputPrice: 10,
    outputPrice: 40,
    priceNote: "High-compute reasoning budget adds cost",
    mmlu: 91.8,
    gpqa: 87.7,
    sweBench: 71.7,
    mathAime: 88,
    multimodal: true,
    extendedThinking: true,
    webSearch: true,
    codeExecution: true,
    openSource: false,
    speed: "slow",
    bestFor: ["Competition math", "Scientific research", "Complex coding tasks", "Logic puzzles"],
    highlight: "ARC-AGI ~88% — best pure-reasoning model in early 2025",
    docsUrl: "https://platform.openai.com/docs/models",
    status: "available",
    lastVerified: "2026-05-01",
  },
  {
    id: "o4-mini",
    name: "o4-mini",
    apiId: "o4-mini",
    provider: "OpenAI",
    providerColor: "#10a37f",
    releaseDate: "Apr 2025",
    releaseDateNum: 202504,
    tier: "reasoning",
    contextWindow: 200,
    outputLimit: 100,
    inputPrice: 1.1,
    outputPrice: 4.4,
    mmlu: 90,
    gpqa: 82.6,
    sweBench: 68.1,
    mathAime: 83,
    multimodal: true,
    extendedThinking: true,
    webSearch: true,
    codeExecution: true,
    openSource: false,
    speed: "medium",
    bestFor: ["Coding at scale", "STEM reasoning on a budget", "Math tutoring"],
    highlight: "Best cost-per-reasoning-step in the o-series",
    docsUrl: "https://platform.openai.com/docs/models",
    status: "available",
    lastVerified: "2026-05-01",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o mini",
    apiId: "gpt-4o-mini",
    provider: "OpenAI",
    providerColor: "#10a37f",
    releaseDate: "Jul 2024",
    releaseDateNum: 202407,
    tier: "efficient",
    contextWindow: 128,
    outputLimit: 16,
    inputPrice: 0.15,
    outputPrice: 0.60,
    priceNote: "Cached input: $0.075/1M",
    mmlu: 82,
    gpqa: null,
    sweBench: null,
    mathAime: null,
    multimodal: true,
    extendedThinking: false,
    webSearch: false,
    codeExecution: false,
    openSource: false,
    speed: "fast",
    bestFor: ["Customer support bots", "Simple classification", "Content moderation"],
    highlight: "40× cheaper than GPT-4o for routine tasks",
    docsUrl: "https://platform.openai.com/docs/models",
    status: "available",
    lastVerified: "2026-05-01",
  },

  // ── Google ────────────────────────────────────────────────────────────────
  {
    id: "gemini-2-5-pro",
    name: "Gemini 2.5 Pro",
    apiId: "gemini-2.5-pro",
    provider: "Google",
    providerColor: "#4285f4",
    releaseDate: "Mar 2025",
    releaseDateNum: 202503,
    tier: "flagship",
    contextWindow: 1000,
    outputLimit: 64,
    inputPrice: 1.25,
    outputPrice: 10,
    priceNote: "Prompts >200k tokens: $2.50/1M in; context caching available",
    mmlu: 90.0,
    gpqa: 84.0,
    sweBench: 63.8,
    mathAime: 86.7,
    multimodal: true,
    extendedThinking: true,
    webSearch: true,
    codeExecution: true,
    openSource: false,
    speed: "medium",
    bestFor: ["1M-token documents", "Video understanding", "Scientific analysis", "Long-context coding"],
    highlight: "1M-token context — best for massive document analysis",
    docsUrl: "https://ai.google.dev/gemini-api/docs/models",
    status: "available",
    lastVerified: "2026-05-01",
  },
  {
    id: "gemini-2-5-flash",
    name: "Gemini 2.5 Flash",
    apiId: "gemini-2.5-flash",
    provider: "Google",
    providerColor: "#4285f4",
    releaseDate: "May 2025",
    releaseDateNum: 202505,
    tier: "efficient",
    contextWindow: 1000,
    outputLimit: 64,
    inputPrice: 0.15,
    outputPrice: 0.60,
    priceNote: "Thinking tokens billed separately at $3.50/1M",
    mmlu: 87.5,
    gpqa: 78.0,
    sweBench: 56.6,
    mathAime: 75,
    multimodal: true,
    extendedThinking: true,
    webSearch: true,
    codeExecution: true,
    openSource: false,
    speed: "fast",
    bestFor: ["High-volume pipelines", "1M-context at low cost", "Multimodal classification"],
    highlight: "1M context at efficient-tier pricing — exceptional value",
    docsUrl: "https://ai.google.dev/gemini-api/docs/models",
    status: "available",
    lastVerified: "2026-05-01",
  },

  // ── Meta ──────────────────────────────────────────────────────────────────
  {
    id: "llama-4-maverick",
    name: "Llama 4 Maverick",
    apiId: "meta-llama/llama-4-maverick",
    provider: "Meta",
    providerColor: "#0866ff",
    releaseDate: "Apr 2025",
    releaseDateNum: 202504,
    tier: "open",
    contextWindow: 1000,
    outputLimit: null,
    inputPrice: 0.27,
    outputPrice: 0.85,
    priceNote: "Via hosted providers (Together, Fireworks, etc.) — free to self-host",
    mmlu: 85.5,
    gpqa: 69.8,
    sweBench: 38,
    mathAime: 49,
    multimodal: true,
    extendedThinking: false,
    webSearch: false,
    codeExecution: false,
    openSource: true,
    speed: "fast",
    bestFor: ["Self-hosted deployments", "European data residency", "Fine-tuning on own data"],
    highlight: "Best open-source multimodal model — run on your own infra",
    docsUrl: "https://ai.meta.com/blog/llama-4-multimodal-intelligence/",
    status: "available",
    lastVerified: "2026-05-01",
  },
  {
    id: "llama-4-scout",
    name: "Llama 4 Scout",
    apiId: "meta-llama/llama-4-scout",
    provider: "Meta",
    providerColor: "#0866ff",
    releaseDate: "Apr 2025",
    releaseDateNum: 202504,
    tier: "open",
    contextWindow: 10000,
    outputLimit: null,
    inputPrice: 0.11,
    outputPrice: 0.34,
    priceNote: "Via hosted providers — free to self-host",
    mmlu: 79.6,
    gpqa: null,
    sweBench: null,
    mathAime: null,
    multimodal: true,
    extendedThinking: false,
    webSearch: false,
    codeExecution: false,
    openSource: true,
    speed: "fast",
    bestFor: ["Entire codebases in context", "Very long document processing"],
    highlight: "10M-token context window — largest of any open model",
    docsUrl: "https://ai.meta.com/blog/llama-4-multimodal-intelligence/",
    status: "available",
    lastVerified: "2026-05-01",
  },

  // ── DeepSeek ──────────────────────────────────────────────────────────────
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    apiId: "deepseek-chat",
    provider: "DeepSeek",
    providerColor: "#1a73e8",
    releaseDate: "Dec 2024",
    releaseDateNum: 202412,
    tier: "open",
    contextWindow: 128,
    outputLimit: 8,
    inputPrice: 0.27,
    outputPrice: 1.10,
    priceNote: "Cache hit: $0.07/1M; free to self-host weights",
    mmlu: 88.5,
    gpqa: 59.1,
    sweBench: 42,
    mathAime: 40,
    multimodal: false,
    extendedThinking: false,
    webSearch: false,
    codeExecution: false,
    openSource: true,
    speed: "fast",
    bestFor: ["Coding assistance", "Cost-sensitive production", "Self-hosted LLM"],
    highlight: "GPT-4-class performance at 20× lower API cost",
    docsUrl: "https://platform.deepseek.com/api-docs/",
    status: "available",
    lastVerified: "2026-05-01",
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    apiId: "deepseek-reasoner",
    provider: "DeepSeek",
    providerColor: "#1a73e8",
    releaseDate: "Jan 2025",
    releaseDateNum: 202501,
    tier: "reasoning",
    contextWindow: 128,
    outputLimit: 64,
    inputPrice: 0.55,
    outputPrice: 2.19,
    priceNote: "Free to self-host weights (MIT license)",
    mmlu: 90.8,
    gpqa: 71.5,
    sweBench: 49.2,
    mathAime: 79.8,
    multimodal: false,
    extendedThinking: true,
    webSearch: false,
    codeExecution: false,
    openSource: true,
    speed: "slow",
    bestFor: ["Math reasoning", "Code generation", "Self-hosted reasoning pipeline"],
    highlight: "o1-level reasoning fully open-source — MIT license",
    docsUrl: "https://platform.deepseek.com/api-docs/",
    status: "available",
    lastVerified: "2026-05-01",
  },

  // ── xAI ──────────────────────────────────────────────────────────────────
  {
    id: "grok-3",
    name: "Grok 3",
    apiId: "grok-3",
    provider: "xAI",
    providerColor: "#111111",
    releaseDate: "Feb 2025",
    releaseDateNum: 202502,
    tier: "flagship",
    contextWindow: 131,
    outputLimit: 16,
    inputPrice: 3,
    outputPrice: 15,
    mmlu: 92.7,
    gpqa: 84.6,
    sweBench: 48,
    mathAime: 93.3,
    multimodal: true,
    extendedThinking: true,
    webSearch: true,
    codeExecution: false,
    openSource: false,
    speed: "medium",
    bestFor: ["Math olympiad problems", "Real-time web questions", "STEM research"],
    highlight: "Highest published AIME score — strong math specialist",
    docsUrl: "https://docs.x.ai/docs",
    status: "available",
    lastVerified: "2026-05-01",
  },

  // ── Mistral ───────────────────────────────────────────────────────────────
  {
    id: "mistral-large-2",
    name: "Mistral Large 2",
    apiId: "mistral-large-latest",
    provider: "Mistral AI",
    providerColor: "#ff7000",
    releaseDate: "Jul 2024",
    releaseDateNum: 202407,
    tier: "balanced",
    contextWindow: 128,
    outputLimit: null,
    inputPrice: 2,
    outputPrice: 6,
    mmlu: 84,
    gpqa: 56.6,
    sweBench: null,
    mathAime: null,
    multimodal: false,
    extendedThinking: false,
    webSearch: false,
    codeExecution: false,
    openSource: false,
    speed: "medium",
    bestFor: ["European data residency (French servers)", "Multilingual", "Function calling"],
    highlight: "Best GDPR-compliant option — EU-hosted infrastructure",
    docsUrl: "https://docs.mistral.ai/getting-started/models/",
    status: "available",
    lastVerified: "2026-05-01",
  },
  {
    id: "codestral-2501",
    name: "Codestral 25.01",
    apiId: "codestral-latest",
    provider: "Mistral AI",
    providerColor: "#ff7000",
    releaseDate: "Jan 2025",
    releaseDateNum: 202501,
    tier: "balanced",
    contextWindow: 256,
    outputLimit: null,
    inputPrice: 0.3,
    outputPrice: 0.9,
    mmlu: null,
    gpqa: null,
    sweBench: null,
    mathAime: null,
    multimodal: false,
    extendedThinking: false,
    webSearch: false,
    codeExecution: true,
    openSource: false,
    speed: "fast",
    bestFor: ["Code completion", "Fill-in-the-middle", "IDE integration"],
    highlight: "Purpose-built for coding — 256k context for entire repos",
    docsUrl: "https://docs.mistral.ai/getting-started/models/",
    status: "available",
    lastVerified: "2026-05-01",
  },
];

export const MODEL_PROVIDERS = [...new Set(AI_MODELS.map(m => m.provider))].sort();
