import type { NewsItem } from "./newsData";

/**
 * Manually verified news added on 23 June 2026.
 * Kept separate from the historical corpus so the daily append-only updater can
 * continue writing to newsData.ts without rewriting this reviewed batch.
 */
export const LATEST_AI_NEWS: NewsItem[] = [
  {
    id: "baseten-raises-1-5b-at-13b-valuation",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 23,
    title: "Baseten Raises $1.5 Billion at $13 Billion Valuation",
    summary: "AI inference infrastructure company Baseten raised $1.5 billion in a round led by Sands Capital and Wellington Management. The company said revenue increased twentyfold over the past year and plans to expand compute capacity, software and hiring.",
    tags: ["Baseten", "Funding", "Inference", "AI Infrastructure"],
    significance: "major",
    provider: "Baseten",
    providerColor: "#7257fa",
    url: "https://www.reuters.com/world/asia-pacific/ai-startup-baseten-hits-13-billion-valuation-australias-blackbird-makes-record-2026-06-23/",
    why_it_matters: "The round shows that serving models efficiently is becoming an investment category as important as training them.",
    what_to_try: "Benchmark one production workload across a frontier API and a dedicated inference platform, including latency and total cost per completed task.",
  },
  {
    id: "european-tech-stocks-ai-debt-pressure",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 23,
    title: "European Tech Stocks Slide as AI Spending Meets Higher Rates",
    summary: "European technology shares fell 2.6% as investors reassessed debt-backed AI capital spending amid expectations of higher interest rates. The wider STOXX 600 also declined, with semiconductor companies among the notable losers.",
    tags: ["Europe", "Markets", "AI Infrastructure", "Finance"],
    significance: "notable",
    provider: "Reuters",
    providerColor: "#ff8000",
    url: "https://www.reuters.com/markets/europe/european-shares-set-open-lower-fed-rate-hike-bets-tech-weakness-weigh-2026-06-23/",
    country: "EU",
    why_it_matters: "AI investment plans are increasingly being judged against financing costs and cash generation rather than growth narratives alone.",
    what_to_try: "Add interest-rate and utilization sensitivities to any AI infrastructure business case before approving capacity commitments.",
  },
  {
    id: "micron-anthropic-memory-storage-agreement",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "Micron and Anthropic Sign AI Memory and Storage Agreement",
    summary: "Micron agreed to supply Anthropic with memory and storage products and made a strategic investment in Anthropic's latest funding round. The companies will analyze how memory and storage interact with the broader infrastructure used to train and serve Claude.",
    tags: ["Anthropic", "Micron", "Claude", "Semiconductors", "AI Infrastructure"],
    significance: "major",
    provider: "Anthropic",
    providerColor: "#d97706",
    url: "https://www.reuters.com/business/micron-anthropic-sign-ai-infrastructure-supply-agreement-2026-06-22/",
    why_it_matters: "Frontier-model economics now depend on co-optimizing memory, storage, networking and accelerators rather than purchasing GPUs in isolation.",
    what_to_try: "Profile memory bandwidth, storage throughput and cache behavior separately when diagnosing an expensive AI workload.",
  },
  {
    id: "reflection-spacex-colossus2-compute-deal",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "Reflection Secures SpaceX Colossus 2 Compute Through 2029",
    summary: "Open-source AI startup Reflection signed a compute agreement with SpaceX for immediate access to Nvidia GB300 systems at the Colossus 2 data center. Reported payments rise to $150 million per month from July 2026 through 2029.",
    tags: ["Reflection AI", "SpaceX", "Nvidia", "Open Source", "Compute"],
    significance: "major",
    provider: "Reflection AI",
    providerColor: "#7257fa",
    url: "https://www.reuters.com/business/media-telecom/ai-startup-reflection-signs-computing-power-deal-with-spacex-2026-06-22/",
    why_it_matters: "Open-model developers are adopting hyperscale, multi-year compute commitments previously associated with only the largest closed labs.",
    what_to_try: "Treat long-term compute agreements as concentration risk and model exit clauses, utilization floors and supplier failure scenarios.",
  },
  {
    id: "qualcomm-modular-acquisition-talks",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "Qualcomm Nears $4 Billion Deal for AI Chip Startup Modular",
    summary: "Qualcomm entered advanced discussions to acquire AI chip software company Modular in a transaction reportedly valuing it at about $4 billion. Modular had been valued at $1.6 billion nine months earlier.",
    tags: ["Qualcomm", "Modular", "Acquisition", "AI Chips", "Compilers"],
    significance: "major",
    provider: "Qualcomm",
    providerColor: "#3253dc",
    url: "https://www.reuters.com/legal/transactional/qualcomm-nearing-deal-ai-chip-startup-modular-bloomberg-news-reports-2026-06-22/",
    why_it_matters: "Chip competition is expanding into developer software and compiler layers that determine whether alternative hardware is practical to adopt.",
    what_to_try: "Separate hardware benchmarks from migration effort when evaluating a non-Nvidia accelerator stack.",
  },
  {
    id: "google-deepmind-a24-filmmaking-partnership",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "Google DeepMind and A24 Form AI Filmmaking Research Partnership",
    summary: "Google DeepMind and independent studio A24 announced a partnership to explore how artificial intelligence can support filmmakers and creative professionals. The agreement brings a frontier AI laboratory into direct research collaboration with a major film studio.",
    tags: ["Google DeepMind", "A24", "Creative AI", "Film", "Research"],
    significance: "notable",
    provider: "Google DeepMind",
    providerColor: "#4285f4",
    url: "https://www.reuters.com/business/media-telecom/google-deepmind-signs-ai-research-deal-with-film-studio-a24-2026-06-22/",
    why_it_matters: "Creative AI development is moving from generic generation tools toward domain-specific workflows designed with professional practitioners.",
    what_to_try: "Map a creative workflow into ideation, pre-production, production and review stages before deciding where AI should assist.",
  },
  {
    id: "ibm-openai-enterprise-security-partnership",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "IBM and OpenAI Partner on Enterprise Security AI",
    summary: "IBM partnered with OpenAI to integrate frontier AI capabilities into enterprise security workflows. The companies said the collaboration is intended to help organizations respond to faster-changing cyber threats.",
    tags: ["IBM", "OpenAI", "Cybersecurity", "Enterprise AI", "Partnership"],
    significance: "major",
    provider: "IBM",
    providerColor: "#0f62fe",
    url: "https://www.reuters.com/technology/ibm-partners-with-openai-enterprise-security-ai-2026-06-22/",
    why_it_matters: "Security operations are becoming one of the first enterprise domains where frontier-model capability can directly affect response time.",
    what_to_try: "Pilot AI on alert triage and evidence summarization first, while keeping containment and remediation actions approval-gated.",
  },
  {
    id: "upscale-ai-190m-extension-2b-valuation",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "Upscale AI Reaches $2 Billion Valuation After Funding Extension",
    summary: "AI networking infrastructure company Upscale AI raised a $190 million extension to its early-stage funding round. The financing brought the company's reported valuation to $2 billion.",
    tags: ["Upscale AI", "Funding", "Networking", "AI Infrastructure"],
    significance: "notable",
    provider: "Upscale AI",
    providerColor: "#7257fa",
    url: "https://www.reuters.com/business/upscale-ai-valued-2-billion-after-funding-extension-2026-06-22/",
    why_it_matters: "Networking bottlenecks are attracting large investments as clusters become bigger and model communication becomes more demanding.",
    what_to_try: "Include network utilization and interconnect cost in GPU-cluster capacity planning instead of treating networking as fixed overhead.",
  },
  {
    id: "openai-gpt-5-5-cyber-upgrade",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "OpenAI Expands GPT-5.5-Cyber for Vetted Security Teams",
    summary: "OpenAI released a more capable and permissive version of GPT-5.5-Cyber for authorized cybersecurity work. Access remains limited to vetted security companies and researchers, alongside new programs for customer-environment defense and international partnerships.",
    tags: ["OpenAI", "GPT-5.5", "Cybersecurity", "Model Update", "Access Control"],
    significance: "major",
    provider: "OpenAI",
    providerColor: "#10a37f",
    url: "https://www.axios.com/2026/06/22/openai-rolls-out-more-capable-version-of-cyber-model",
    why_it_matters: "Capability-based access controls are emerging as a deployment model for systems whose defensive value and misuse potential rise together.",
    what_to_try: "Document user vetting, permitted environments and audit requirements before deploying a high-capability cyber model.",
  },
  {
    id: "nvidia-halos-robotics-safety",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "Nvidia Launches Halos Safety Architecture for Humanoid Robots",
    summary: "Nvidia introduced Halos for Robotics, combining software, compute, sensors and inspection capabilities into a safety architecture for humanoid systems. Agility is the first customer and plans to use it in deployments serving companies including Amazon and Toyota.",
    tags: ["Nvidia", "Robotics", "Humanoids", "Safety", "Embodied AI"],
    significance: "major",
    provider: "Nvidia",
    providerColor: "#76b900",
    url: "https://www.axios.com/2026/06/22/nvidia-humanoid-ai-robotics",
    why_it_matters: "Physical AI needs an auditable safety stack spanning perception, compute and validation before robots can operate beside people at scale.",
    what_to_try: "Define safe states and independent inspection checks before measuring a robot's task-completion performance.",
  },
  {
    id: "nvidia-rubin-warm-liquid-cooling",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "Nvidia Details 45°C Liquid Cooling for Rubin Data Centers",
    summary: "Nvidia said its Rubin-generation reference design can use recirculated liquid at 113°F, or 45°C, reducing dependence on chillers and cooling towers. The design targets lower cooling-related water and energy use, though electricity generation and construction impacts remain.",
    tags: ["Nvidia", "Rubin", "Data Centers", "Cooling", "Sustainability"],
    significance: "major",
    provider: "Nvidia",
    providerColor: "#76b900",
    url: "https://www.axios.com/2026/06/22/nvidia-data-center-water-solution",
    why_it_matters: "Thermal design is becoming a strategic constraint on where AI capacity can be built and how quickly it can receive approval.",
    what_to_try: "Evaluate cooling technology using total facility water and power, not only server-level efficiency claims.",
  },
  {
    id: "chevron-microsoft-project-kilby-power-deal",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "Chevron Signs 20-Year Power Deal for Microsoft AI Campus",
    summary: "Chevron agreed to supply a new Microsoft data center in West Texas under a 20-year arrangement tied to Project Kilby. The planned co-located generation facility could produce 2.67 gigawatts and is expected to come online in 2028 if approved.",
    tags: ["Microsoft", "Chevron", "Data Centers", "Energy", "AI Infrastructure"],
    significance: "major",
    provider: "Microsoft",
    providerColor: "#0078d4",
    url: "https://www.axios.com/newsletters/axios-closer-f56c702f-09eb-4f59-a2f6-0f193e8670e9",
    why_it_matters: "AI campuses are increasingly bringing dedicated generation with them because grid access has become a deployment bottleneck.",
    what_to_try: "Include power-delivery timing, fuel-price exposure and emissions scenarios in data-center sourcing decisions.",
  },
  {
    id: "digitalbridge-arclight-power-acquisition",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "DigitalBridge Buys ArcLight as AI Investors Chase Power Assets",
    summary: "DigitalBridge agreed to acquire power infrastructure developer ArcLight Capital for $1.1 billion. The transaction reflects a wider trend in which data-center investors are buying generation and grid-development expertise to secure capacity faster.",
    tags: ["DigitalBridge", "ArcLight", "Acquisition", "Energy", "Data Centers"],
    significance: "notable",
    provider: "DigitalBridge",
    providerColor: "#5060a8",
    url: "https://www.reuters.com/business/energy/data-center-investors-buy-up-power-developers-race-build--reeii-2026-06-22/",
    why_it_matters: "Control of power development is becoming a competitive advantage for AI infrastructure owners facing long grid queues.",
    what_to_try: "Score infrastructure partners on interconnection rights and power-development capability, not only rack availability.",
  },
  {
    id: "european-firms-diversify-ai-providers-us-curbs",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "European Companies Diversify AI Providers After U.S. Restrictions",
    summary: "European firms including Siemens, Renault and Orange are spreading workloads across U.S., European, Chinese and open models after U.S. restrictions highlighted supplier-access risk. The shift is strengthening interest in on-premise deployment, open weights and digital sovereignty.",
    tags: ["Europe", "AI Sovereignty", "Open Source", "Enterprise AI", "Policy"],
    significance: "major",
    provider: "Reuters",
    providerColor: "#ff8000",
    url: "https://www.reuters.com/legal/litigation/us-curbs-ai-spur-european-firms-spread-risk-2026-06-22/",
    country: "EU",
    why_it_matters: "Model access can now change because of geopolitics, making provider concentration an operational risk rather than only a procurement concern.",
    what_to_try: "Create a model portability plan with one alternative provider and one locally deployable model for each critical workflow.",
  },
  {
    id: "five-eyes-frontier-ai-cyber-warning",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "Five Eyes Warns Frontier AI Could Transform Cyberattacks Within Months",
    summary: "The Five Eyes intelligence alliance warned that frontier models could rapidly increase both offensive and defensive cyber capabilities within months rather than years. The joint statement urged faster patching, reduced exposure and proactive adoption of AI-enabled defense.",
    tags: ["Five Eyes", "Cybersecurity", "Frontier Models", "Government", "Risk"],
    significance: "major",
    provider: "Five Eyes",
    providerColor: "#34495e",
    url: "https://www.reuters.com/world/asia-pacific/five-eyes-intelligence-alliance-warns-that-new-ai-models-pose-urgent-cyber-risk-2026-06-22/",
    why_it_matters: "The warning moves advanced-model cyber risk from a laboratory forecast into near-term national security planning.",
    what_to_try: "Shorten patch-service-level targets for internet-facing critical systems and test whether AI can help defenders meet them.",
  },
  {
    id: "trump-ai-public-stake-policy-options",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "U.S. Debate Opens Over Public Stakes in Leading AI Firms",
    summary: "Policy proposals under discussion in the United States include targeted taxes, equity in exchange for federal support and public wealth mechanisms tied to leading AI companies. The debate centers on whether citizens should share more directly in returns from publicly enabled AI growth.",
    tags: ["United States", "Policy", "Public Investment", "OpenAI", "Anthropic"],
    significance: "notable",
    provider: "Reuters",
    providerColor: "#ff8000",
    url: "https://www.reuters.com/legal/transactional/three-ways-trump-could-get-stake-ai-firms-us-2026-06-22/",
    why_it_matters: "The policy conversation is expanding from regulating AI harms to deciding how the economic upside of AI should be distributed.",
    what_to_try: "Track public subsidies and infrastructure support alongside private returns when assessing the social value of an AI investment.",
  },
  {
    id: "south-australia-ai-data-center-strategy",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "South Australia Unveils Dedicated AI Data Center Strategy",
    summary: "South Australia outlined a strategy to attract large AI data centers using renewable energy and international fiber connectivity. Proposed legislation would govern development and resource use, while identified projects include facilities approaching one gigawatt.",
    tags: ["Australia", "Data Centers", "AI Infrastructure", "Energy", "Government"],
    significance: "notable",
    provider: "Government of South Australia",
    providerColor: "#d71920",
    url: "https://www.adelaidenow.com.au/news/south-australia/state-election/premier-peter-malinauskas-reveals-data-centre-strategy-to-capitalise-on-artificial-intelligence-boom/news-story/01165be8355402a8963629bc46c535aa",
    why_it_matters: "Regional governments are starting to treat AI infrastructure as industrial policy that must coordinate energy, water, fiber and planning.",
    what_to_try: "Use a single infrastructure scorecard covering power, water, connectivity, permits and workforce when comparing AI-campus locations.",
  },
  {
    id: "reliance-jamnagar-ai-backbone-22-languages",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 20,
    title: "Reliance Plans India AI Backbone Supporting 22 Languages",
    summary: "Reliance Industries said its AI execution phase will center on infrastructure in Jamnagar and services spanning 22 Indian languages. The company also plans to evolve MyJio into a personal AI assistant and add generative media capabilities across its platforms.",
    tags: ["Reliance", "India", "Multilingual AI", "AI Infrastructure", "Consumer AI"],
    significance: "major",
    provider: "Reliance Industries",
    providerColor: "#153a78",
    url: "https://m.economictimes.com/news/company/corporate-trends/reliance-agm-2026-key-takeaways-jio-ipo-ai-satellite-connectivity-jioteleframe-more-10-biggest-announcements-from-ambanis-vision-for-the-future/articleshow/131853757.cms",
    why_it_matters: "Large regional platforms are pairing domestic compute with language coverage that global products often treat as secondary.",
    what_to_try: "Evaluate an assistant separately in the languages and code-switching patterns used by its actual audience.",
  },
  {
    id: "china-space-computing-innovation-center",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 20,
    title: "China Organizes National Push for Orbiting AI Data Centers",
    summary: "China established a Space Computing Industry Innovation Center to coordinate satellite, launch, chip and AI organizations around orbital computing. The initiative targets space-hardened chips, low-power models and distributed space-ground infrastructure.",
    tags: ["China", "Space Computing", "AI Infrastructure", "Satellites", "Semiconductors"],
    significance: "notable",
    provider: "Space Computing Industry Innovation Center",
    providerColor: "#de2910",
    url: "https://www.tomshardware.com/tech-industry/data-centers/china-unifies-tech-sector-to-build-grid-free-orbiting-satellite-ai-data-centers-challenging-elon-musks-spacex-beijings-forced-chip-and-satellite-alliance-announced-a-week-before-musks-ai1-reveal",
    why_it_matters: "Orbital computing is moving from isolated proposals toward coordinated national and commercial infrastructure programs.",
    what_to_try: "Separate workloads that benefit from in-orbit processing from those that would be constrained by launch cost and ground-link bandwidth.",
  },
  {
    id: "europe-2031-ai-sovereignty-scenario",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 20,
    title: "Europe 2031 Scenario Drives Debate Over AI Sovereignty",
    summary: "A speculative scenario portraying an economically weakened Europe dependent on U.S. and Chinese AI gained attention among European policymakers. Supporters say it clarifies strategic risk, while critics warn that fictional forecasts can overstate uncertain infrastructure and adoption assumptions.",
    tags: ["Europe", "AI Sovereignty", "Policy", "Scenario Planning", "Data Centers"],
    significance: "notable",
    provider: "The Guardian",
    providerColor: "#052962",
    url: "https://www.theguardian.com/technology/2026/jun/20/europe-sleepwalking-ai-disaster-us-china",
    country: "EU",
    why_it_matters: "Narratives about AI competition are influencing real infrastructure and regulatory choices even when their assumptions remain contested.",
    what_to_try: "For every strategic AI scenario, document leading indicators and a plausible counter-scenario before using it to justify investment.",
  },
  {
    id: "john-jumper-leaves-deepmind-for-anthropic",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 19,
    title: "AlphaFold Scientist John Jumper Leaves DeepMind for Anthropic",
    summary: "Nobel Prize-winning scientist John Jumper, a co-creator of AlphaFold, announced he is leaving Google DeepMind to join Anthropic. The move adds a leading AI-for-science researcher to Anthropic amid intensifying competition for frontier talent.",
    tags: ["Anthropic", "Google DeepMind", "AlphaFold", "AI Science", "Talent"],
    significance: "major",
    provider: "Anthropic",
    providerColor: "#d97706",
    url: "https://www.reuters.com/technology/us-scientist-john-jumper-leave-google-deepmind-anthropic-2026-06-19/",
    why_it_matters: "Frontier laboratories are competing not only on models and compute but on small teams of researchers who can open entirely new application domains.",
    what_to_try: "Track critical knowledge concentration and succession risk in AI teams rather than counting only total headcount.",
  },
  {
    id: "europa-frontier-ai-grand-challenge-winner",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 19,
    title: "EU Selects EUROPA to Build Open Frontier Model",
    summary: "The European Commission selected the Domyn-led EUROPA consortium to build an open frontier AI model covering all 24 official EU languages. The challenge sought proposals at a scale above 400 billion parameters using European high-performance computing resources.",
    tags: ["European Union", "EUROPA", "Open Source", "Multilingual AI", "EuroHPC"],
    significance: "major",
    provider: "European Commission",
    providerColor: "#003399",
    url: "https://italy.representation.ec.europa.eu/notizie-ed-eventi/notizie/la-commissione-assegna-al-consorzio-europa-il-frontier-ai-grand-challenge-2026-06-19_it",
    country: "EU",
    why_it_matters: "Europe is combining sovereign compute, open weights and multilingual coverage in a direct attempt to build strategic model capacity.",
    what_to_try: "Follow the release license, training-data disclosure and language-by-language evaluations rather than relying on aggregate benchmarks.",
  },
  {
    id: "sweden-ai-cyber-financial-system-warning",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 19,
    title: "IMF Warning Highlights Sweden's Exposure to AI-Driven Cyber Risk",
    summary: "The IMF and Swedish cybersecurity specialists warned that AI can shorten the time needed to discover and exploit software vulnerabilities. Sweden's extensive digitalization and dependence on shared services such as BankID and Swish were identified as factors that could amplify coordinated disruption.",
    tags: ["Sweden", "Cybersecurity", "Financial Stability", "BankID", "Swish"],
    significance: "major",
    provider: "Svenska Dagbladet",
    providerColor: "#f4c400",
    url: "https://www.svd.se/a/3pm3PP/imf-varnar-ai-hotar-banker-potentiell-chock",
    country: "SE",
    why_it_matters: "Highly connected national platforms create efficiency but can also turn shared software weaknesses into systemic risk.",
    what_to_try: "Map shared digital dependencies across payments, identity and suppliers, then rehearse a simultaneous multi-provider outage.",
  },
  {
    id: "brazil-r2b-ai-supercomputer-plan",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 19,
    title: "Brazil Prepares R$2 Billion Domestic AI Supercomputer",
    summary: "Brazil's federal government is expected to announce a supercomputer project worth nearly R$2 billion for training AI models domestically. The system is planned for operation in 2027 and is intended to support health, agriculture, climate research and public digital services.",
    tags: ["Brazil", "Supercomputer", "AI Sovereignty", "Public Investment", "Research"],
    significance: "major",
    provider: "Brazilian Federal Government",
    providerColor: "#009c3b",
    url: "https://exame.com/inteligencia-artificial/brasil-pode-ganhar-supercomputador-de-r-2-bilhoes-para-treinar-ia-no-pais/",
    country: "BR",
    why_it_matters: "Domestic compute could reduce dependence on foreign infrastructure and make nationally important datasets easier to use under local governance.",
    what_to_try: "Evaluate public-compute programs on utilization access, allocation transparency and measurable research outputs, not peak capacity alone.",
  },
  {
    id: "brazil-government-ai-solution-reuse-bank",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 19,
    title: "Brazil Government AI Lab Plans Reusable Solutions Bank",
    summary: "Brazil's federal AI innovation laboratory plans to activate a repository of reusable government AI solutions during the second half of 2026. The effort aims to prevent agencies from rebuilding similar systems independently and to spread proven implementations across public bodies.",
    tags: ["Brazil", "Government", "Public Sector AI", "Reuse", "Digital Services"],
    significance: "notable",
    provider: "LIIA",
    providerColor: "#009c3b",
    url: "https://convergenciadigital.com.br/governo/laboratorio-de-inteligencia-artificial-do-governo-vai-ativar-banco-de-reuso-de-solucoes-no-2o-semestre/",
    country: "BR",
    why_it_matters: "Reusable components can move public-sector AI from scattered pilots toward shared infrastructure and repeatable governance.",
    what_to_try: "Package every successful internal AI pilot with an owner, data contract, risk record and deployment checklist so another unit can reuse it.",
  },
  {
    id: "brazil-stf-platform-accountability-ai",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 19,
    title: "Brazil's Supreme Court President Calls for Platform Accountability",
    summary: "STF President Edson Fachin said digital platforms must be held responsible as artificial intelligence and other technologies reshape public debate. He also called for the judiciary to address the ethical consequences of AI while protecting human dignity.",
    tags: ["Brazil", "STF", "Platform Regulation", "AI Ethics", "Policy"],
    significance: "notable",
    provider: "Supremo Tribunal Federal",
    providerColor: "#005ca9",
    url: "https://www.bol.uol.com.br/noticias/2026/06/19/fachin-defende-responsabilizacao-das-plataformas-digitais-diante-dos-impactos-da-tecnologia.htm",
    country: "BR",
    why_it_matters: "Brazil's platform-liability debate is increasingly incorporating AI-generated content, automated amplification and accountability.",
    what_to_try: "Maintain clear provenance, escalation and appeal paths for any AI system that affects public-facing content decisions.",
  },
  {
    id: "brazil-tupann-rainfall-ai-three-hour-forecast",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 21,
    title: "Brazilian Tupann Model Forecasts Rain Three Hours Ahead",
    summary: "Researchers at IMPA developed Tupann, an AI model that forecasts rainfall up to three hours ahead using satellite data rather than depending on ground radar. Google Brazil and the City of Rio supported the project, and Rio has already used the system.",
    tags: ["Brazil", "Climate AI", "IMPA", "Google", "Weather"],
    significance: "major",
    provider: "IMPA",
    providerColor: "#009c3b",
    url: "https://portal.rondoniaovivo.com/noticia/geral/2026/06/21/chuva-em-3h-inteligencia-artificial-criado-pela-inpa-e-eficiente-em-previsao-de-chuva.html",
    country: "BR",
    why_it_matters: "Satellite-based nowcasting can extend early-warning capability to regions without dense weather-radar coverage.",
    what_to_try: "Evaluate climate models separately on ordinary weather and rare extreme events, where historical training data may be weakest.",
  },
  {
    id: "cli-universe-terminal-agent-dataset",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "CLI-Universe Releases 6,000 Verified Terminal-Agent Trajectories",
    summary: "Researchers introduced CLI-Universe, a synthesis and verification pipeline for executable terminal-agent tasks. Fine-tuning Qwen3-32B on its 6,000-trajectory dataset achieved 33.4% on Terminal-Bench 2.0, reported as a new open-data result for models at or below 32 billion parameters.",
    tags: ["Research", "AI Agents", "Terminal Agents", "Dataset", "Benchmark"],
    significance: "notable",
    provider: "arXiv",
    providerColor: "#b31b1b",
    url: "https://arxiv.org/abs/2606.22883",
    why_it_matters: "Carefully verified training tasks can improve agent performance more efficiently than simply scaling model size or synthetic volume.",
    what_to_try: "Require executable tests and fail-to-pass verification when generating synthetic tasks for coding agents.",
  },
  {
    id: "intent-governed-tool-authorization-agents",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 22,
    title: "Researchers Propose Intent-Governed Authorization for AI Agents",
    summary: "A new paper proposes Intent-Governed Access Control, a server-side authorization layer that checks whether tool calls and payloads remain consistent with the user's expressed request. The design ensures that inferred intent can narrow existing permissions but cannot expand them.",
    tags: ["Research", "AI Agents", "Authorization", "Security", "Tool Use"],
    significance: "major",
    provider: "arXiv",
    providerColor: "#b31b1b",
    url: "https://arxiv.org/abs/2606.22916",
    why_it_matters: "Static API scopes are insufficient when an agent can choose among many actions and construct consequential payloads autonomously.",
    what_to_try: "Bind every write-capable agent action to the current user request, a preview of impact and a stable audit reason code.",
  },
  {
    id: "vista-architect-tumor-board-ehr-graph",
    date: "Jun 2026",
    dateNum: 202606,
    dateDay: 21,
    title: "VISTA Architect Uses Provenance Graphs for Tumor Board Preparation",
    summary: "VISTA Architect converts longitudinal electronic health records into a provenance-linked clinical knowledge graph for repeated downstream use. In a thoracic oncology demonstration across 1,180 patients, it reported 96.4% accuracy on 17,700 evaluations and prepared a 30-patient cohort in about 2.2 minutes.",
    tags: ["Research", "Healthcare AI", "Knowledge Graphs", "EHR", "Agents"],
    significance: "major",
    provider: "Stanford Medicine",
    providerColor: "#8c1515",
    url: "https://arxiv.org/abs/2606.22692",
    why_it_matters: "Persistent, provenance-linked structure can outperform repeatedly prompting or retrieving from raw clinical records while preserving traceability.",
    what_to_try: "For repeated document workflows, compare one-time structured extraction with repeated RAG on accuracy, latency and reviewability.",
  },
];
