import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const dataPath = join(__dirname, "../src/data/useCases.json");
const rawData = JSON.parse(readFileSync(dataPath, "utf8")) as unknown[];
const count = rawData.length;

const out = join(__dirname, "../src/lib/useCasesCount.generated.ts");
writeFileSync(
  out,
  `// Auto-generated by scripts/generate-use-cases-count.ts — do not edit by hand.\n` +
    `// Regenerated on every \`npm run build\` (via the \`prebuild\` script).\n` +
    `export const USE_CASES_COUNT = ${count};\n`,
  "utf8",
);
console.log(`✓ USE_CASES_COUNT written → src/lib/useCasesCount.generated.ts (${count})`);
